disabled_rules:
  - trailing_whitespace
  - force_cast
  - todo

excluded:
  - Pods

# Customizations
line_length: 150
force_cast: warning
identifier_name:
  min_length: 1
  max_length: 50
type_name:
  max_length: 50
function_body_length:
  - 60
file_length:
  - 500
